print("\nNombre: Ruvalcaba Valverde Miguel Angel")
print("--------------Ejemplo-----------------")
print("--Imagina una funsion de esta manera--")
print("Funasion: Ritual antiguo para invocar demonios.")
print("Codigo de la Funsion: Demonio que se puede invocar.")
print("Para invocar invocar al demonio Reddoticantel, tienes que desir las palabras antiguas del ritual.")
def kilaquezoxt():
    print("El demonio Reddoticantel fue invocado")
print("kilaquezoxt")
kilaquezoxt()
print("y el demonio fue invocado, ese es el ejemplo. =P")
print("--------------------------------------")
print("Resultado: \n")
